# Generated by Django 3.2.5 on 2021-08-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.IntegerField(default=1)),
                ('pre_skills', models.BooleanField(default=0)),
                ('starting_point', models.IntegerField(default=1)),
                ('English_level', models.IntegerField(default=1)),
                ('time_interval', models.IntegerField(default=1)),
                ('skill_pros', models.BooleanField(default=1, max_length=1)),
                ('skill_profit', models.BooleanField(default=1, max_length=1)),
                ('skill_attraction', models.BooleanField(default=1, max_length=1)),
                ('i_e_parameter', models.CharField(default='I', max_length=1)),
                ('s_n_parameter', models.CharField(default='S', max_length=1)),
                ('t_f_parameter', models.CharField(default='T', max_length=1)),
                ('p_j_parameter', models.CharField(default='P', max_length=1)),
                ('clusters', models.FloatField(default=1)),
            ],
        ),
    ]
