# Generated by Django 3.2.5 on 2021-08-03 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_cluster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cluster',
        ),
    ]
