# Generated by Django 3.2.5 on 2021-08-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_cluster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cluster',
        ),
    ]
